# Generated by Django 4.2.11 on 2025-03-29 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ПІБ водія')),
                ('license_number', models.CharField(max_length=20, unique=True, verbose_name='Номер посвідчення')),
                ('license_type', models.CharField(choices=[('B', 'Легкові авто'), ('C', 'Вантажівки'), ('D', 'Автобуси')], max_length=1, verbose_name='Категорія прав')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('experience', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)], verbose_name='Стаж (роки)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('hire_date', models.DateField(verbose_name='Дата найму')),
                ('birth_date', models.DateField(verbose_name='Дата народження')),
            ],
            options={
                'verbose_name': 'Водій',
                'verbose_name_plural': 'Водії',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['license_number'], name='drivers_dri_license_ce5f7e_idx'), models.Index(fields=['is_active'], name='drivers_dri_is_acti_7c5f39_idx')],
            },
        ),
    ]
