# Generated by Django 5.2 on 2025-04-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
