# Generated by Django 4.2.11 on 2025-03-29 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('clients', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField(verbose_name='Адреса подачі')),
                ('destination', models.TextField(verbose_name='Адреса призначення')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('confirmed', 'Підтверджене'), ('in_progress', 'Виконується'), ('completed', 'Завершене'), ('cancelled', 'Скасоване')], default='new', max_length=20, verbose_name='Статус')),
                ('payment_type', models.CharField(choices=[('cash', 'Готівка'), ('card', 'Картка'), ('invoice', 'Рахунок')], default='cash', max_length=10, verbose_name='Тип оплати')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Додаткові нотатки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.client', verbose_name='Клієнт')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='drivers.driver', verbose_name='Водій')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='fleet.vehicle', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'), models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'), models.Index(fields=['client', 'status'], name='orders_orde_client__7fa500_idx')],
            },
        ),
    ]
