# Generated by Django 4.2.11 on 2025-03-29 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я клієнта")),
                ('phone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефону має бути у форматі: '+380123456789'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='Переваги')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний клієнт')),
                ('license_number', models.CharField(max_length=100, verbose_name='Дані документа')),
                ('license_type', models.CharField(choices=[('Passport', 'Паспорт'), ('Driver license', 'Посвідчення водія'), ('Car license', 'Паспорт на авто')], max_length=100, verbose_name='Підтверджуючий документ')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
                'ordering': ['-registration_date'],
                'indexes': [models.Index(fields=['phone'], name='clients_cli_phone_164f4c_idx'), models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx')],
            },
        ),
    ]
