# Generated by Django 4.2.11 on 2025-03-29 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Рік випуску')),
                ('license_plate', models.CharField(max_length=15, unique=True, verbose_name='Держномер')),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Седан'), ('minivan', 'Мінівен'), ('suv', 'Позашляховик'), ('bus', 'Автобус')], max_length=10, verbose_name='Тип транспорту')),
                ('capacity', models.PositiveIntegerField(verbose_name='Кількість місць')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Електро'), ('hybrid', 'Гібрид')], max_length=10, verbose_name='Тип палива')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='Пробіг (км)')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Дата останнього ТО')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступний')),
                ('purchase_date', models.DateField(verbose_name='Дата покупки')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість покупки')),
            ],
            options={
                'verbose_name': 'Транспортний засіб',
                'verbose_name_plural': 'Транспортні засоби',
                'ordering': ['-purchase_date'],
                'indexes': [models.Index(fields=['license_plate'], name='fleet_vehic_license_8e5cca_idx'), models.Index(fields=['is_available'], name='fleet_vehic_is_avai_3af511_idx'), models.Index(fields=['vehicle_type'], name='fleet_vehic_vehicle_6cfc86_idx')],
            },
        ),
    ]
