# Generated by Django 5.2 on 2025-04-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(default=4, help_text='Кількість пасажирів', verbose_name='Місткість'),
        ),
    ]
